/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage2;

import java.awt.BasicStroke;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.ArrayList;

/**
 *
 * @author PERSONAL
 */
public class PanelJuego extends javax.swing.JPanel {
    int x,y;
    Esfera objEsferaGlobal;
    ArrayList<Esfera> nomArrayList = new ArrayList<Esfera>();
    Graphics2D g2;
    /**
     * Creates new form PanelJuego
     */
    public PanelJuego() {
        initComponents();
    }
    public void recibirEsfera(Esfera obj){
        nomArrayList.add(obj);
    }
    
    public void paint(Graphics g){
        super.paint(g);
        g2 = (Graphics2D)g;
        for(Esfera b: nomArrayList){
            g2.fill(b.crearEsfera());
        }
        
        repaint();
        removeAll();
    }
    public void paint1(Graphics g){
        super.paint(g);
        g2 = (Graphics2D)g;
        for(Esfera b: nomArrayList){
            g2.fill(b.crearEsfera1());
            
        }
        repaint();
        removeAll();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        jButton1.setText("Jugar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jButton1)
                .addContainerGap(288, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jButton1)
                .addContainerGap(164, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.paint2();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void paint2(){
        //jButton1.setVisible(false);
        g2.setStroke(new BasicStroke(15.0f)); 
        g2.drawLine (0, 0, 0, 400);
        g2.setStroke(new BasicStroke(15.0f)); 
        g2.drawLine (0, 400, 400, 400);
        g2.setStroke(new BasicStroke(15.0f)); 
        g2.drawLine (400, 400, 400, 0);
        g2.setStroke(new BasicStroke(15.0f)); 
        g2.drawLine (0, 0, 400, 0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
